# Generated by Django 2.2.28 on 2024-12-04 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20241203_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='volume',
            field=models.CharField(default=0, max_length=10, verbose_name='Объем'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 4, 15, 39, 12, 912611), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 4, 15, 39, 12, 912611), verbose_name='Дата комментария'),
        ),
        migrations.DeleteModel(
            name='DrinkVolume',
        ),
    ]
