# Generated by Django 2.2.28 on 2024-12-07 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20241208_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='model',
            field=models.CharField(choices=[('product', 'Product'), ('drink', 'Drink')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 8, 0, 21, 14, 315337), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 8, 0, 21, 14, 316333), verbose_name='Дата комментария'),
        ),
    ]
