# Generated by Django 2.2.28 on 2024-12-07 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20241208_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='model',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 8, 0, 25, 33, 70599), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 8, 0, 25, 33, 71596), verbose_name='Дата комментария'),
        ),
    ]
